### ISSUE TITLE
Experiment with plotting

### ISSUE THREAD

**Issue by thanasipantazides** [foxsi/GSE-FOXSI-4#1]
### End goal

Eventually, we want a GUI that can display detector images, light curves, and spectra. These need to refresh relatively quickly (every second or so) during flight, so it is important to test speed/latency. Before we have complete knowledge of the downlink packet format/log file format, it would be good to practice rendering the desired plot types in pyqtgraph from higher-level data (numpy arrays or something). Then, once the log file format is fully defined, we can translate each packet data to a useful format for plotting.

### Some helpful (?) links

- [pyqtgraph documentation](https://pyqtgraph.readthedocs.io/en/latest/)
- [Example plotting](https://brainflow.org/2021-07-05-real-time-example/) (on a timer) with pyqtgraph---this is likely what we will want to do for flight, i.e. read the log file in batches on a timer, rather than every time a new packet shows up in the log
- [pyROOT](https://root.cern/manual/python/)---Python interface to ROOT.

### Todo

- [x] Make some representative plots using pyqtgraph. How easy is the library to use? Does it take forever to refresh a plot with new data?

pyqtgraph alternatives:

- [x] Consider [embedding ROOT in Qt](https://root.cern/manual/embed_root_in_gui/) for plotting. This looks more complicated.
- [x] Consider [matplotlib with blit turned on](https://matplotlib.org/stable/tutorials/advanced/blitting.html).
